minimumReleaseAgeExclude:
  - '@mehm8128/rehype-toc'

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  fast-xml-parser@>=4.1.3 <5.3.5: '>=5.3.5'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  hono@<4.11.10: '>=4.11.10'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
